import environ

env = environ.Env()
environ.Env.read_env()

MAX_SMS_BATCH_REQUEST = env.int('MAX_SMS_BATCH_REQUEST', 5)
MAX_SUBMIT_ATTEMPTS = env.int('MAX_SUBMIT_ATTEMPTS', 2)
MAX_GATEWAY_HTTP_TIMEOUT = env.int('MAX_GATEWAY_HTTP_TIMEOUT', 10)
SPAN_FAILURE_MAX_THRESHOLD_NOTIFY = env.int('SPAN_FAILURE_MAX_THRESHOLD_NOTIFY', 5)
LOG_RETENTION_DAYS = env.int('LOG_RETENTION_DAYS', 2)