# Generated by Django 3.2.3 on 2021-05-25 23:19

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('error_message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvalidSMSMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('recipient', models.CharField(max_length=255)),
                ('error_reason', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('bulk_id', models.UUIDField(blank=True, null=True)),
                ('text', models.TextField()),
                ('recipient', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('pages', models.PositiveIntegerField(blank=True, default=0)),
                ('submitted_ok', models.BooleanField(default=False)),
                ('submitted_ok_at', models.DateTimeField(null=True)),
                ('failed', models.BooleanField(default=False, help_text='given up')),
                ('failed_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'SMS Message',
                'verbose_name_plural': 'SMS Messages',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SMSQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submit_attempts', models.PositiveIntegerField(default=0)),
                ('last_submit_attempt_at', models.DateTimeField(blank=True, help_text='last time send_sms was attempted', null=True)),
                ('next_submit_attempt_at', models.DateTimeField(blank=True, help_text='next time send_sms will be attempted', null=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sms.smsmessage')),
                ('send_span', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='span_sms_messages', to='gateway.span')),
            ],
            options={
                'ordering': ('-last_submit_attempt_at',),
            },
        ),
    ]
