# Generated by Django 3.2.3 on 2021-05-25 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmessage',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invalidsmsmessage',
            name='message',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.smsmessage'),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='sms_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.smsmessage'),
        ),
    ]
