# Generated by Django 3.2.3 on 2021-05-26 03:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSMessageStateLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('submitted', 'Submitted OK'), ('queued', 'Queued'), ('delayed', 'Delayed'), ('failed', 'Failed'), ('new', 'New')], default='new', max_length=30)),
                ('state_message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='smsmessage',
            name='failed',
        ),
        migrations.RemoveField(
            model_name='smsmessage',
            name='failed_at',
        ),
        migrations.RemoveField(
            model_name='smsmessage',
            name='submitted_ok',
        ),
        migrations.RemoveField(
            model_name='smsmessage',
            name='submitted_ok_at',
        ),
        migrations.DeleteModel(
            name='ErrorLog',
        ),
        migrations.AddField(
            model_name='smsmessagestatelog',
            name='sms_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='sms.smsmessage'),
        ),
    ]
