# Generated by Django 3.2.3 on 2021-05-26 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_auto_20210525_2122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smsqueue',
            options={'ordering': ('-last_modified',)},
        ),
        migrations.RemoveField(
            model_name='smsmessagestatelog',
            name='sms_message',
        ),
        migrations.RemoveField(
            model_name='smsqueue',
            name='last_submit_attempt_at',
        ),
        migrations.RemoveField(
            model_name='smsqueue',
            name='next_submit_attempt_at',
        ),
        migrations.AddField(
            model_name='smsmessagestatelog',
            name='sms_message_id',
            field=models.UUIDField(db_index=True, default='bab8534b-a422-47a3-baff-bfc59613bfe9'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smsqueue',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
