# Generated by Django 3.2.3 on 2021-05-26 04:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_auto_20210525_2200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smsqueue',
            options={'ordering': ('-created',)},
        ),
        migrations.RemoveField(
            model_name='smsqueue',
            name='last_modified',
        ),
        migrations.AddField(
            model_name='smsqueue',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smsqueue',
            name='next_submit_attempt_at',
            field=models.DateTimeField(blank=True, help_text='next time send_sms will be attempted', null=True),
        ),
        migrations.AlterField(
            model_name='smsmessagestatelog',
            name='state',
            field=models.CharField(choices=[('submitted', 'Submitted OK'), ('queued', 'Queued'), ('delayed', 'Delayed'), ('failed', 'Failed'), ('processing', 'Processing')], default='queued', max_length=30),
        ),
    ]
