# Generated by Django 3.2.3 on 2021-05-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0006_auto_20210525_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmessage',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('new', 'New'), ('failed', 'Failed'), ('error', 'Error')], default='new', max_length=30),
        ),
    ]
