# Generated by Django 3.2.3 on 2021-06-01 03:11

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvalidSMSMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('recipient', models.CharField(max_length=255)),
                ('error_reason', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('bulk_id', models.UUIDField(blank=True, null=True)),
                ('text', models.TextField()),
                ('recipient', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('pages', models.PositiveIntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('new', 'New'), ('failed', 'Failed'), ('error', 'Error'), ('queued', 'Queued')], default='new', max_length=30)),
            ],
            options={
                'verbose_name': 'SMS Message',
                'verbose_name_plural': 'SMS Messages',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SMSMessageStateLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sms_message_id', models.UUIDField(db_index=True)),
                ('state', models.CharField(choices=[('submitted', 'Submitted OK'), ('delayed', 'Delayed'), ('failed', 'Failed'), ('processing', 'Processing'), ('error', 'Error')], default='processing', max_length=30)),
                ('state_reason', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-timestamp', 'sms_message_id'),
            },
        ),
        migrations.CreateModel(
            name='SMSQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submit_attempts', models.PositiveIntegerField(default=0)),
                ('next_submit_attempt_at', models.DateTimeField(blank=True, help_text='next time send_sms will be attempted', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sms.smsmessage')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
