# Generated by Django 3.2.3 on 2021-06-01 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sms', '0001_initial'),
        ('gateway', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmessage',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='send_span',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='span_sms_messages', to='gateway.span'),
        ),
        migrations.AddField(
            model_name='invalidsmsmessage',
            name='message',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.smsmessage'),
        ),
    ]
