# Generated by Django 3.2.3 on 2021-05-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_auto_20210525_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smsmessagestatelog',
            old_name='state_message',
            new_name='state_reason',
        ),
        migrations.AlterField(
            model_name='smsmessagestatelog',
            name='state',
            field=models.CharField(choices=[('submitted', 'Submitted OK'), ('queued', 'Queued'), ('delayed', 'Delayed'), ('failed', 'Failed'), ('processing', 'Processing'), ('error', 'Error')], default='queued', max_length=30),
        ),
    ]
