# Generated by Django 3.2.3 on 2021-05-29 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0003_auto_20210526_0055'),
        ('sms', '0007_smsmessage_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsqueue',
            name='send_span',
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='send_span',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='span_sms_messages', to='gateway.span'),
        ),
    ]
