# Generated by Django 3.2.3 on 2021-05-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0008_auto_20210529_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smsmessagestatelog',
            options={'ordering': ('-timestamp', 'sms_message_id')},
        ),
        migrations.AlterField(
            model_name='smsmessage',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('new', 'New'), ('failed', 'Failed'), ('error', 'Error'), ('queued', 'Queued')], default='new', max_length=30),
        ),
        migrations.AlterField(
            model_name='smsmessagestatelog',
            name='state',
            field=models.CharField(choices=[('submitted', 'Submitted OK'), ('delayed', 'Delayed'), ('failed', 'Failed'), ('processing', 'Processing'), ('error', 'Error')], default='processing', max_length=30),
        ),
    ]
