# Generated by Django 3.2.3 on 2021-05-26 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='span',
            name='last_sms_sent_at',
        ),
        migrations.RemoveField(
            model_name='span',
            name='message_failure_next_frame_reset',
        ),
    ]
