# Generated by Django 3.2.3 on 2021-05-31 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0003_auto_20210526_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='span',
            name='total_messages_sent_month_last_reset',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='span',
            name='total_messages_sent_today_last_reset',
            field=models.DateField(null=True),
        ),
    ]
