# Generated by Django 3.2.3 on 2021-05-25 23:19

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('api_url', models.URLField(blank=True)),
                ('api_username', models.CharField(max_length=255)),
                ('api_password', models.CharField(max_length=255)),
                ('sms_sending_disabled', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Span',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('channel_id', models.CharField(max_length=3)),
                ('SIM_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('SIM_IMSI', models.CharField(blank=True, max_length=30)),
                ('sms_sending_disabled', models.BooleanField(default=False)),
                ('total_messages_sent', models.PositiveIntegerField(default=0)),
                ('total_messages_sent_today', models.PositiveIntegerField(default=0)),
                ('total_messages_sent_month', models.PositiveIntegerField(default=0)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('message_failure_count', models.PositiveIntegerField(default=0)),
                ('message_failure_next_frame_reset', models.DateTimeField(blank=True, null=True)),
                ('last_sms_sent_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spans', to='gateway.device')),
            ],
        ),
        migrations.CreateModel(
            name='SendProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('strategy', models.CharField(choices=[('SINGLE', 'Single'), ('DISTRIBUTE', 'Distribute'), ('RANDOM', 'Random')], default='SINGLE', max_length=20)),
                ('is_default', models.BooleanField(default=True)),
                ('spans', models.ManyToManyField(to='gateway.Span')),
            ],
        ),
    ]
