# Generated by Django 3.2.3 on 2021-05-31 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0004_auto_20210530_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='span',
            name='total_messages_sent_month_last_reset',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='span',
            name='total_messages_sent_today_last_reset',
            field=models.DateTimeField(null=True),
        ),
    ]
